name: maplibre_gl_web
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    implements: maplibre_gl
    platforms:
      web:
        pluginClass: MaplibreGlPlugin
        fileName: maplibre_gl_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  maplibre_gl_platform_interface:
    path: ../maplibre_gl_platform_interface
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
